<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>

		<RootNamespace>MiMFa.Engine.DEAL.JS.Environment</RootNamespace>
		<EnableDefaultCompileItems>true</EnableDefaultCompileItems>

		<Company>MiMFa</Company>
		<Product>DEAL.JS</Product>
		<Authors>Mohammad Fathi (MiMFa)</Authors>

		<ApplicationIcon />
		<OutputType>Exe</OutputType>
		<StartupObject>MiMFa.Engine.DEAL.JS.Environment.Program</StartupObject>

		<PackageId>MiMFa DEAL.JS - Environment</PackageId>

		<!-- ClearScript native package is win-x86 -->
		<PlatformTarget>x86</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.ClearScript.V8" Version="7.5.1.1" />
		<PackageReference Include="Microsoft.ClearScript.V8.Native.win-x86" Version="7.5.1.1" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
		<None Include="LICENSE" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MiMFa DEAL.JS - Compiler\MiMFa DEAL.JS - Compiler.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="DEAL.JS\Library\final.djs">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="DEAL.JS\Library\manual.djs">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="DEAL.JS\Library\initial.djs">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>